import { NextRequest, NextResponse } from "next/server";
import { getWalletsForRequest } from "@/lib/wallet-session";
import { getMuseumAccess } from "@/lib/museum-access";
import { createAdminClient } from "@/lib/supabase/server";
const REACTIONS = ["linger", "dangerous", "favorite-tonight"] as const;
async function holder(request: NextRequest) { const wallet = getWalletsForRequest(request)?.[0]; if (!wallet) return null; const access = await getMuseumAccess(wallet); return access.allowed ? wallet : null; }
export const dynamic = "force-dynamic";
export async function GET(request: NextRequest) { const wallet = await holder(request); const contentId = request.nextUrl.searchParams.get("contentId"); if (!wallet || !contentId) return NextResponse.json({ error: "Museum pass required" }, { status: 403 }); const admin = createAdminClient(); await admin.from("museum_reactions").delete().lte("expires_at", new Date().toISOString()); const { data, error } = await admin.from("museum_reactions").select("reaction, wallet").eq("content_id", contentId).gt("expires_at", new Date().toISOString()); if (error) return NextResponse.json({ error: error.message }, { status: 500 }); const counts = Object.fromEntries(REACTIONS.map((reaction) => [reaction, (data ?? []).filter((item) => item.reaction === reaction).length])); return NextResponse.json({ counts, mine: (data ?? []).filter((item) => item.wallet === wallet).map((item) => item.reaction) }); }
export async function POST(request: NextRequest) { const wallet = await holder(request); const body = await request.json().catch(() => null) as { contentId?: string; reaction?: string } | null; if (!wallet || !body?.contentId || !REACTIONS.includes(body.reaction as typeof REACTIONS[number])) return NextResponse.json({ error: "Invalid reaction" }, { status: 400 }); const { error } = await createAdminClient().from("museum_reactions").upsert({ content_id: body.contentId, wallet, reaction: body.reaction, expires_at: new Date(Date.now() + 7_200_000).toISOString() }, { onConflict: "content_id,wallet,reaction" }); if (error) return NextResponse.json({ error: error.message }, { status: 500 }); return NextResponse.json({ ok: true }); }
